apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  type: NodePort
  selector:
    app: weather-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32111 # You can change this to any available port number above 30000
